### ISSUE TITLE
This does not actually have a description

### ISSUE THREAD

**Issue by fatso83** [josephnedher/meetbot#5]
"Attend classes". I am not sure what that means? Do you mean it shows your picture and acts on your behalf, or what?

**Comment by ghost** [comment]
It enters the meeting only, nothing else. Doesn't show pictures, acts in your behalf nor exits the meeting.

**Comment by fatso83** [comment]
OK, I thought it actually was supposed to _do_ something, but that's fine :)

**Comment by ghost** [comment]
I mean, It does something... the base is pretty solid and it would be possible to implement more things, which is actually one of my plans, but I haven't really started to work on it so I can't say if it'll be that different from this one
